# Generated by Django 3.0.8 on 2020-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20200914_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
