# Generated by Django 3.0.8 on 2020-09-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_recipe_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likeCount',
        ),
    ]
