# Generated by Django 3.0.8 on 2020-09-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='NULL', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, default='NULL', null=True, upload_to='images/'),
        ),
    ]
