# Generated by Django 3.0.8 on 2020-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200814_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageurl',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
